-   hosts: [ dev ]
    become: yes
    become_user: kyagi
    tasks: 
        - cron: 
            name: "update kiatsu"
            job: "/home/kyagi/project/kiatsu/kiatsu-scripts/bin/kiatsu.sh 2>&1 >> /home/kyagi/project/kiatsu/log/kiatsu.log"
            minute: "0"
            state: present